src/lib/sites/types.ts
* Removes non-mutable properties
* Adds missed properties
Closes #2
=> Fixes type for update site payload

src/lib/sites/types.ts
* Adds the new_external_uid prop
closes #3
=> Fixes invalid duplicate site payload type

README.md
* Updates parameters to example promise response to remove object
closes #11
=> Corrects response example in readme

tests/account.tests.ts
=> Accounts Testing Update

tests/collections.tests.ts
Redid Collections Testing
-Includes Collections, Rows, and Fields testing
=> Collections Test Update

tests/page.tests.ts
=> Pages test update

tests/plan.tests.ts
=> Plans test update

tests/site.tests.ts
- Added New Site Tests
- Some Discrepencies from Dev Docs, needs review for some commands
=> Site Updated Testing

tests/content.tests.ts
- Updated tests to include formatted raw_body input
- Updated input injected_content for testing inject content command for more coverage (includes all 3 content attributes now)
=> Content Create Injected Content Command -- Issue 20

src/lib/other/SSL.ts, tests/other.tests.ts
- Changed Create Command from GET to POST
- Changed Renew Command from GET to POST
- Changed Delete Command from GET to DELETE
- Added back tests for all SSL commands in tests file and verified
=> Other SSL Commands -- Issue 23

src/lib/collections/types.ts, tests/collection.tests.ts
- Changed external_details object from required to optional
- Changed parameters external_endpoint and external_id within external details object from required to optional
- Uncommented and fixed Update Collections test
=> Collections Update Command -- Issue 16

src/lib/reporting/types.ts, tests/reporting.test.ts
- Removed parameter last_days for consistency with Dev Docs (unnecessary)
- Removed comments regarding issue from Reporting tests file (verified)
- Changed type of lastDays in types file to be either a string or a number
- Updated tests for unpublish/publish in tests file, removed unnecessary comments (verified)
=> Reporting Unpublish/Publish -- Issue 31

src/lib/collections/types.ts, tests/collection.tests.ts
- Added customer_lock parameter to types file for Update Collection Command
- Modified test for Update Collection Command in tests file (verified)
=> Collections Update Command -- Issue 40

src/lib/reporting/types.ts, tests/reporting.test.ts
- Removed data_granularity param, revised dataGranularity to correctly enum instead of taking any string
- Updated Analytics test in tests file (verified)
=> Reporting Analytics Command -- Issue 33

src/lib/accounts/types.ts, tests/account.tests.ts
- Added missing permissions into types folder
- Updated Grant Site test parameter
=> Permissions Grant Site Access -- Issue 39

src/lib/pages/types.ts, src/lib/pages/v2.ts, tests/page.tests.ts
* Adds header_html param to the definition
* Fixes payload type to set no_index to boolean
* Uncomments and updates broken test
closes #4
=> Fixes update page call to send header_html param

src/lib/sites/Sites.ts, src/lib/sites/types.ts, tests/site.tests.ts
* Mark template id as a required param in type and definition
* Add site_data to definition
* Update test to include site_data
closes #36
=> Updates reset site to require template id

src/lib/sites/types.ts
=> Allows template id to by of type string or number when creating a site

src/lib/collections/types.ts, tests/collection.tests.ts
* Makes body an array of strings instead of objects
* uncomments test
closes #17
=> Fixes payload for row delete call

src/lib/apps/content/Content.ts, src/lib/content/Content.ts, src/lib/content/MultiLocation.ts, src/lib/content/types.ts, tests/content.tests.ts
* Updates content library payload type to resemble actual usage
* Updates location object to resemble actual usage
* Updates types used in code
* Updates tests to ensure payload matches registered type
closes #9
=> Updates types on content library object

README.md, package-lock.json, package.json, src/lib/APIEndpoint.ts, src/lib/base.ts, src/lib/http.ts, tests/network.tests.ts, yarn.lock
* Handle request errors and retry if specified, else reject
* Add a timeout config and default so https.request can timeout if needed
* Update readme to include new timeout config
* Re-enable nyc coverage testing
* Add network error tests to catch this sort of error.
Fixes #82
=> Fixes issue where request errors were not being handled

tests/account.tests.ts, tests/app/site.tests.ts, tests/collection.tests.ts, tests/content.tests.ts, tests/other.tests.ts, tests/page.tests.ts, tests/plan.tests.ts, tests/reporting.tests.ts, tests/site.tests.ts, tests/template.tests.ts, tests/urlrule.tests.ts
* Adds async/await to all 'it' functions
closes #66
=> Updates tests to be synchronous to ease debugging

src/index.ts, src/lib/ecomm/Ecomm.ts, src/lib/ecomm/Products.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
* Adds new Ecomm namespace
* Adds Products namespace and create method
* Adds Types for product payload and response
* Adds Create Product test
Closes #78
=> Adds method for create product endpoint

src/lib/ecomm/Products.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
- updated types file
- update products file
- updated ecomm tests file
=> Added Delete Ecomm Product

src/lib/APIEndpoint.ts, src/lib/ecomm/Products.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
- updated types file
- updated products file
- updated ecomm tests file
=> Added Update Ecomm Product

src/lib/ecomm/Products.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
- updated products file
- updated types file
- updated ecomm tests file
=> Added Get Ecomm Product

src/lib/ecomm/Products.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
- updated products file
- updated types file
- updated ecomm tests file
=> Added List Ecomm Products

src/lib/ecomm/Gateways.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
* Adds method for get gateway
* Adds new types/refactor
* Adds test/refactor
Closes #72
=> Adds the get gateway endpont

src/lib/ecomm/Gateways.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
* Adds method to list gateway
* Adds types
* Adds test to new method
Closes #73
=> Adds list gateway endpoint

src/lib/ecomm/Gateways.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
* Adds new ecomm method
* Adds new types
* Adds test for new method
Closes #74
=> Adds update gateway endpoint

src/lib/ecomm/Gateways.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
* Adds new method
* Adds new types
* Adds test for new method
Closes #75
=> Adds delete gateway endpoint

src/lib/ecomm/Ecomm.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
* Adds a new method
* Adds new types
* Adds test for new method
Closes #68
=> Adds update ecomm settings endpoint

package.json, src/lib/sites/Sites.ts, src/lib/sites/Theme.ts, src/lib/sites/types.ts, tests/site.tests.ts
Added Update and Get Site Theme Endpoints
- Added tests to tests.ts file
=> Update Site Theme + Get Site Theme

package.json, src/lib/reporting/Activities.ts, src/lib/reporting/Analytics.ts, src/lib/reporting/types.ts, tests/reporting.tests.ts
-Updated Analytics/Activities endpoints to take query params
-Updated appropriate tests to reflect this change in reporting.tests.ts file
=> Get analytics/activities issue113

src/lib/reporting/Activities.ts, src/lib/reporting/Analytics.ts, src/lib/reporting/types.ts, tests/reporting.tests.ts
* Get Analytics
- Updated Analytics.ts file with query params
- Changed Analytics test in reporting.tests.ts
* Updated types and tests files for analytics endpoint
* Added Activites Endpoint Query Param changes as well
- updated activities.ts
- updated reporting.tests.ts file to include new activities test case
* Updated reporting.tests.ts file
- Changed analytics/activities tests to appropriately match other tests in the file
=> Get analytics/activities issue113 (#136)

src/lib/ecomm/Carts.ts, src/lib/ecomm/Ecomm.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
Branch name made before consolidation of commands from List category
- Added List Carts and Get Cart commands
=> Ecomm Carts

src/lib/ecomm/Ecomm.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
- Added Get Ecomm Settings Endpoing
- Added appropriate testing
=> Get ecomm settings -- 114

src/lib/ecomm/Ecomm.ts, src/lib/ecomm/Orders.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
- Added List Orders and Get Order Endpoints
- Added tests to ecomm.tests.ts for List Orders and Get Order endpoints
=> Ecomm Order Endpoints

src/lib/ecomm/Categories.ts, src/lib/ecomm/Ecomm.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
- Added Get Categories, Get Category, Create Category, Update Category, and Delete Category Endpoints
- Create Category.ts file, updated Ecomm.ts file, updated types.ts file
- Added appropriate tests in ecomm.tests.ts file
=> Ecomm Categories Endpoints

src/lib/ecomm/Ecomm.ts, src/lib/ecomm/Options.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
- Added Options.ts file
- Updated Ecomm.ts file, types.ts file
- Added appropriate tests to ecomm.tests.ts file
=> Ecomm Product Options Endpoints

src/lib/ecomm/Ecomm.ts, src/lib/ecomm/Variations.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
- Added Variations.ts file, updated Ecomm.ts file
- Added tests for variations endpoints in ecomm.tests.ts file
- Minor fixes on type and test of Confirm Payment endpoint
=> Ecomm Variations Endpoints

src/lib/ecomm/Products.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
- Updated Payload/Responses for Product Endpoints
- Updated ecomm.tests.ts file
=> Update Ecomm Product Endpoints

src/lib/sites/Sites.ts, src/lib/sites/types.ts
- Updated Get Site Response
- Updated Create/Update Site Payloads
=> Site Payloads/Responses

package-lock.json, package.json, src/lib/sites/Sites.ts, src/lib/sites/types.ts
- Updated Get Site Response
- Updated Create/Update Site Payloads
=> Site Payloads/Responses (#160)

README.md, src/lib/apps/ecomm/Ecomm.ts, src/lib/apps/ecomm/Options.ts, tests/app/ecomm.tests.ts
- Added App Store Ecomm Product Option Endpoints
- Updated ecomm.ts file
- Added Options.ts file
- Added tests for Product Options in ecomm.tests.ts file
- Updated README with new Product Option Endpoints
=> App Store Ecomm Product Options

README.md, src/lib/apps/ecomm/Ecomm.ts, src/lib/apps/ecomm/Orders.ts, src/lib/ecomm/types.ts, tests/app/ecomm.tests.ts
- Added List Orders, Get Order, and Update Order Endpoints for App Store Ecomm
- Updated Ecomm.ts in apps folder
- Added Orders.ts in apps folder
- Updated types.ts file to include Update Order payload and response
- Updated ecomm.tests.ts file to include new Order Endpoint tests
- Updated README with new Order Endpoints
=> App Store Ecomm Orders Endpoints

.vscode/settings.json, README.md, src/lib/apps/ecomm/Ecomm.ts, src/lib/apps/ecomm/Options.ts, src/lib/apps/ecomm/Orders.ts, src/lib/apps/ecomm/Payments.ts, tests/app/ecomm.tests.ts
- Added Payments Endpoints for App Store
- Created new Payments.ts file
- Updated Ecomm.ts file
- Added new tests for Payments Endpoints in ecomm.tests.ts file
- Updated README with new Payments Endpoints
- Added Header Authorization Check to other ecomm app store endpoints that were missing it
=> App Store Ecomm Payments Endpoints

README.md, src/lib/apps/ecomm/Ecomm.ts, src/lib/apps/ecomm/Gateways.ts, tests/app/ecomm.tests.ts
- Added App Store Ecomm Payment Gateway Endpoints
- Updated Ecomm.ts file
- Added appropriate tests in ecomm.tests.ts file
- Updated README to include new endpoints
=> App Store Ecomm Payment Gateways

README.md, src/lib/apps/ecomm/Carts.ts, src/lib/apps/ecomm/Ecomm.ts, tests/app/ecomm.tests.ts
- Added Appstore Ecomm Carts Endpoints
- Updated ecomm.ts file
- Added appropriate tests to ecomm.tests.ts file
- Updated README with new endpoints
=> Appstore Ecomm Carts

src/lib/apps/manifest/Manifest.ts, src/lib/apps/manifest/types.ts, tests/app/manifest.tests.ts
- Updated Manifest types in types.ts file
- Created new test file and added appropriate tests in manifest.tests.ts file
=> App Store Manifest Endpoints

src/lib/apps/tokens/Tokens.ts, src/lib/apps/tokens/types.ts, tests/app/token.tests.ts
- Cleaned up tokens.ts file
- Cleaned up types.ts file
- Cleaned up tokens.tests.file
=> App Store Create New Access Token Endpoint

README.md, src/index.ts, src/lib/diyeditor/Diyeditor.ts, src/lib/diyeditor/types.ts, tests/diyeditor.tests.ts
- Added new folder for Simple Editor endpoints (diyeditor)
- Created Diyeditor.ts file for new Simple Editor Endpoints
- Added Update Simple Editor Settings Endpoint to Diyeditor.ts file
- Created types.ts file
- Created diyeditor.tests.ts file for new Simple Editor Endpoint tests
- Added test for Update Simple Editor Settings endpoint
- Updated index.ts file to include new diyEditor extension functionality
- Updated README to include new Simple Editor Endpoint
=> Simple Editor

src/lib/APIEndpoint.ts, src/lib/base.ts, tests/config.tests.ts
- Added bearer token authentication as alternative to user/pass
- Added test in config.tests.ts file to showcase this new functionality
=> Bearer Token

README.md, src/lib/pages/types.ts, src/lib/pages/v2.ts, tests/page.tests.ts
- Added Create Page Endpoint
- Fixed payloads for other Pages endpoint calls as well as responses
- Added test for Create Page Endpoint
- Updated tests for other Page API Endpoints
- Updated README with new Create Page Endpoint
=> Create Page Endpoint/General Pages Endpoints Fixes

README.md, src/lib/pages/Pages.ts, src/lib/pages/elements.ts, src/lib/pages/types.ts, tests/page.tests.ts
- Added Page Elements Endpoints under pages subfolder
- Updated types file to include various Page Elements payloads and responses
- Updated pages.test.ts file to include new Page Elements Endpoints tests
- Updated README to include new Page Elements Endpoints
=> Page Elements Endpoints

README.md, src/index.ts, src/lib/sections/Sections.ts, src/lib/sections/types.ts, tests/section.tests.ts
- Added new sections folder containing Sections Endpoints and accompanying types.ts file
- Created new Sections Endpoints tests in new test file section.tests.ts
- Updated README to include new endpoints
=> Sections Endpoints

README.md, src/index.ts, src/lib/blog/Blog.ts, src/lib/blog/types.ts, tests/blog.tests.ts.ts
- Added Blog Endpoints
- Created new blog folder with accompanying types.ts file for new Blog Endpoints
- Created corresponding blog.tests.ts file for Blog Endpoints
- Updated README
=> Blog Endpoints

README.md, src/lib/apps/content/Content.ts, src/lib/apps/content/Locations.ts, src/lib/apps/ecomm/Ecomm.ts, src/lib/ecomm/types.ts, tests/app/content.tests.ts, tests/app/ecomm.tests.ts, tests/ecomm.tests.ts
- Added App Ecomm Settings Endpoints
- Updated/fixed App Content and App Content Locations Endpoints
- Added tests for app ecomm settings and app content/content locations endpoints
- Updated README to include app ecomm settings and app content/content locations endpoints
=> App ecomm settings

README.md, package-lock.json, src/lib/apps/ecomm/Orders.ts, tests/app/ecomm.tests.ts, yarn.lock
- Added app store refund endpoints
- Added appropriate tests to ecomm.tests.ts file in app folder
- Updated README
=> App Store Ecomm Refunds Endpoints

.github/workflows/codeql-analysis.yml, .github/workflows/node.js.yml, README.md
* Adding link in TOC to new beta config
* Updating workflows to deprecate node 14 and adding node 20
=> Updating README

README.md, src/lib/apps/pages/Pages.ts, tests/app/account.tests.ts, tests/app/page.tests.ts, tests/app/site.tests.ts
- Added test for Appstore Accounts and Pages
- Updated Pages endpoint call to correctly use v2 types
- Updated Appstore Sites tests file
- Updated README to include new + more Appstore Endpoints
=> AppStore Test Update

README.md, src/lib/apps/ecomm/Ecomm.ts, src/lib/apps/ecomm/Variations.ts, tests/app/ecomm.tests.ts
- Added Get and Update Product Variation endpoints to app store segment
- Added appropriate get and update tests to app store ecomm tests file
- Updated README to include new Get and Update product variation endpoints on app store side
=> App Store Product Variation Endpoints

README.md, src/lib/apps/ecomm/Ecomm.ts, src/lib/apps/ecomm/Shipping.ts, tests/app/ecomm.tests.ts
- Added Ecomm Shipping Providers Endpoints to app store segment
- Added appropriate tests to app store ecomm tests file
- Updated README to include new App Store Ecomm Shipping Providers Endpoints
=> App Store Ecoom Shipping Providers Endpoints

README.md, src/index.ts, src/lib/apps/Apps.ts, src/lib/base.ts, src/lib/sites/types.ts, src/lib/snippets/Snippets.ts, src/lib/snippets/types.ts, tests/snippets.tests.ts.ts
- Added Snippets endpoints
- Added appropriate types file
- Updated index.ts file to include new snippets path
- Create accompanying snippets tests for the new endpoints
- Updated README to include new Snippets endpoints
=> Snippets Endpoints

src/lib/content/types.ts, tests/content.tests.ts
- Updated types file for update content library endpoint's payload to appropriate have the business_hours parameter desiganted as an array of objects
- Updated content.tests.ts file to show this new change
=> Update Content Library Payload Fix

src/lib/collections/types.ts, tests/collection.tests.ts
- Updated response bodies for list and get collection endpoints
- Updated tests file accordingly
=> Collections Response Body Updates

src/lib/accounts/types.ts
- Updated the Permissions types file to include new permissions
=> Grant Site Access Permissions Update

README.md, src/lib/blog/Blog.ts, src/lib/blog/types.ts, tests/blog.tests.ts.ts
- Added new Blog API Endpoints
- Updated Blog types file to include new endpoints' payloads and responses
- Updated blog tests file
- Updated README
=> Blog API Endpoints

src/lib/ecomm/types.ts, tests/app/ecomm.tests.ts, tests/ecomm.tests.ts
- Fixed the cart settings types for the Get and Update Ecomm Settings API Endpoints
- Updated the tests on the partner and app side respectively
=> Ecomm Settings Endpoints

src/lib/apps/Apps.ts, src/lib/apps/collections/Collections.ts, src/lib/apps/collections/Fields.ts, src/lib/apps/collections/Rows.ts, src/lib/apps/collections/types.ts, tests/app/collection.tests.ts, yarn.lock
- Added the integrationhub collection endpoints on the appstore class
=> Adding app store collection endpoints

src/lib/apps/ecomm/Ecomm.ts, src/lib/apps/ecomm/Store.ts, src/lib/ecomm/Ecomm.ts, src/lib/ecomm/Store.ts, src/lib/ecomm/types.ts, tests/app/ecomm.tests.ts, tests/ecomm.tests.ts
- Added Ecomm Store methods as indicated on the docs here ([docs](https://developer.duda.co/reference/ecomm-store))
- Added App Store Ecomm Store methods as indicated on the docs here ([docs](https://developer.duda.co/reference/app-ecomm-store))
=> Adding Ecomm Store Methods

README.md, src/lib/ecomm/Ecomm.ts, src/lib/ecomm/Groups.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
- Added new Ecomm Tax Groups Endpoints
- Updated ecomm types files
- Added appropriate tests to testing file
- Updated README to include new Ecomm Tax Groups Endpoints
- Added Ecomm Store, App Ecomm Store, App Collections, App Rows, and App Fields to README
=> Ecomm Tax Groups + README Updates

README.md, src/lib/ecomm/Ecomm.ts, src/lib/ecomm/Zones.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
- Added Ecomm Tax Zones and Ecomm Tax Zone Rates Endpoints
- Created new Zones.ts file for the new endpoints under ecomm folder
- Updated types file appropriately
- Added new tests to ecomm.tests.ts file for the new endpoints
- Updated README to include the new endpoints
=> Ecomm Tax Zones and Ecomm Tax Zone Rates Endpoints

README.md, src/lib/accounts/types.ts, src/lib/blog/types.ts, src/lib/ecomm/types.ts, src/lib/sites/Sites.ts, src/lib/sites/types.ts, tests/blog.tests.ts.ts, tests/ecomm.tests.ts, tests/site.tests.ts
- Added List Sites Endpoint that was previously missing from sdk (also updated README to reflect this change)
- Updated site object in types file
- Updated ecomm settings object in types file
- Updated SSO targets in types file
- Updated blog post object in types file
=> General Type Updates

src/lib/collections/types.ts, tests/collection.tests.ts
- Updated types file for create/update collection payloads to include new custom headers parameter
- Updated tests file appropriately
=> Create/Update Collection Custom Headers

README.md, src/lib/collections/types.ts, src/lib/ecomm/Orders.ts, src/lib/ecomm/types.ts, tests/ecomm.tests.ts
- Added Create External Order Endpoint to orders.ts
- Updated types.ts file appropriately
- Updated tests.ts file to include new endpoint
- Updated README to include new endpoint
- Updated types file for collections endpoints to function properly
=> Create External Ecomm Order Endpoint

src/lib/apps/ecomm/Store.ts, tests/app/ecomm.tests.ts
- Fixed issue with path to remove multiscreen
- Fixed appropriate test
=> App Get Store Endpoint (#253)

README.md, src/lib/apps/swh/SWH.ts, src/lib/apps/swh/types.ts, tests/app/site.tests.ts, tests/app/swh.tests.ts
- Added Publish Site Wide HTML Appstore Endpoint
- Updated swh types file
- Updated appropriate tests file
- Updated README to include the new endpoint
=> Publish Site Wide HTML Appstore Endpoint

src/lib/APIEndpoint.ts, src/lib/apps/Apps.ts
- added _refreshing as an in class parameter to not lose context
- added skipPreRequest override, to avoid token renewal multiplicity
=> Fix: changing preRequest logic and variable for token renewal
